# version: '3.1'

services:
  # hellosvc:
  #   image: nginxdemos/hello:latest
  #   ports: 
  #     - 80:80

  # # 第一次手動請求憑證
  # certbot-init:
  #   image: certbot/certbot
  #   container_name: certbot-init
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --email doittwhite@gmail.com -d rag.helenfit.com --agree-tos --force-renewal
  #   depends_on:
  #     - nginx  # 確保 Nginx 在 certbot 前啟動

  # 自動更新憑證
  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $!; certbot renew >> /var/log/certbot-renew.log 2>&1; done'
    restart: unless-stopped

  nginx:
    image: nginx:1.25.5
    # container_name: jdp-nginx-dev-1
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
      - MAINTENANCE_MODE=0
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./maintenance.html:/usr/share/nginx/html/maintenance.html
    depends_on:
      - sideproj-ui
      # - 3-3-joint-defense-platform-api
      # - jointdefense-ui-dev

  mongo:
    image: mongo:5.0.15
    restart: always
    volumes:
      - ./mongodata:/data/db
    ports:
      - 38018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  3-3-joint-defense-platform-api:
    # image: ${CONTAINER_REGISTRY}/itri/3-3-joint-defense-platform-api:0.0.1-src
    image: itri/3-3-joint-defense-platform-api:0.0.4-src
    restart: always
    volumes:
      - ./info_images:/app/app/static/info_images
      - ../image/backend/app:/app/app
    ports:
      - 31244:80
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      DOCS_URL: /docs
      OPENAPI_URL: /openapi.json
      LOG_LEVEL: debug
    depends_on:
      - mongo
    container_name: jdp-api-dev-1

  jointdefense-ui-dev:
    # image: ${CONTAINER_REGISTRY}/itri/3-3-joint-defense-platform-ui:0.0.0
    # image: jointdefense-ui-dev:latest
    image: itri/joint-defense-platform-ui:1.0.5
    restart: always
    # volumes:
    #   - ../image/frontend:/app
    # ports:
    #   - 17281:3000
    # env_file:
    #   - .env
    # command: yarn start
    # container_name: jdp-ui-dev-1

  sideproj-ui:
    image: sideproj-ui:0.1.2
    restart: always
    # ports:
    #   - 17281:3000
    environment:
      VUE_APP_API_HOST: ${VUE_APP_API_HOST}
      VUE_APP_DEV_MODE: ${VUE_APP_DEV_MODE}
